  run_name: null
  use_memmap: true
  train_dataset: "openwebtext_train.uint16.bin"
  val_dataset: "openwebtext_val.uint16.bin"
  epochs: 10000
  batch_size: 3
  context_length: 1024
  lr_max: 0.001
  lr_min: 0.00001
  warmup_iters: 50
  cosine_cycle_iters: 5000
  out_dir: null
  device: "cuda"
  seed: 93
  run_number: 1
  save_every: 5000
  vocab_size: 32000
  hidden_dimension: 1024
  num_layers: 24
  num_heads: 16
  rope_theta: 10000.0

  betas: [0.9, 0.99]
  weight_decay: 0.01

  use_post_norm: false
  remove_rope: false
  remove_rmsnorm: false
  use_bias: false